#!/data/data/com.termux/files/usr/bin/bash -e
# colors

red='\033[1;31m'                                                                                                        yellow='\033[1;33m'
blue='\033[1;34m'
reset='\033[0m'

echo 'Install Metasploit Device 6.0'
sleep 2
curl -LO https://github.com/termux/termux-packages/files/3995119/metasploit_5.0.65-1_all.deb.gz
gunzip metasploit_5.0.65-1_all.deb.gz
dpkg -i metasploit_5.0.65-1_all.deb
apt -f install

printline
printf "\n${yellow} Now you can enjoy Metasploit in your Termux :)\n Don't forget to like my hard work for termux and many other things\n"
printline
printline
printf "\n${blue} [∆] My official email:${yellow}               lkpandey950@gmail.com\n"
printf "$blue [∆] My gitbub:${yellow}          https://github.com/The-X-Team-Debug/\n"
printf "$blue [∆] My YouTube channel:${yellow}  https://m.youtube.com/channel/UCqtmKGqlVcRkFmq9cdgNppA\n"
printline
printf "$reset"
